# Generated by Django 2.2.1 on 2019-05-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('asistencia', models.IntegerField(verbose_name='Asistencia')),
                ('puntualidad', models.IntegerField(verbose_name='Puntualidad')),
                ('presencia', models.IntegerField(verbose_name='Buena Presencia')),
                ('cliente', models.IntegerField(verbose_name='Orientaion/Atencion al Cliente')),
                ('equipo', models.IntegerField(verbose_name='Trabajo en Equipo')),
                ('compromiso', models.IntegerField(verbose_name='Compromiso')),
                ('iniciativa', models.IntegerField(verbose_name='Iniciativa')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
    ]
