# Generated by Django 2.2.1 on 2019-05-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=200)),
                ('encargado', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locales',
                'ordering': ['denominacion'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='local_id',
            field=models.ManyToManyField(to='sucursal.local'),
        ),
    ]
