# Generated by Django 2.2.1 on 2019-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_auto_20190522_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='compromiso',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='iniciativa',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='presencia',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='puntualidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='antiguedad',
            field=models.IntegerField(default=1, verbose_name='Antigüedad'),
            preserve_default=False,
        ),
    ]
