# Generated by Django 2.2.1 on 2019-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0003_auto_20190523_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='evalua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.IntegerField(verbose_name='Asistencia')),
                ('puntualidad', models.IntegerField(verbose_name='Puntualidad')),
                ('presencia', models.IntegerField(verbose_name='Buena Presencia')),
                ('cliente', models.IntegerField(verbose_name='Orientaion/Atencion al Cliente')),
                ('equipo', models.IntegerField(verbose_name='Trabajo en Equipo')),
                ('compromiso', models.IntegerField(verbose_name='Compromiso')),
                ('iniciativa', models.IntegerField(verbose_name='Iniciativa')),
            ],
            options={
                'verbose_name': 'evalua',
                'verbose_name_plural': 'evaluan',
            },
        ),
    ]
