# Generated by Django 2.2.1 on 2019-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0004_evalua'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalua',
            name='id_evaluando',
            field=models.ManyToManyField(to='sucursal.empleado'),
        ),
    ]
