# Generated by Django 2.2.1 on 2019-06-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0006_auto_20190619_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalua',
            name='id_evaluando',
        ),
        migrations.AddField(
            model_name='evalua',
            name='id_evaluando',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sucursal.empleado'),
            preserve_default=False,
        ),
    ]
