# Generated by Django 2.2.1 on 2019-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0007_auto_20190619_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalua',
            name='asistencia',
            field=models.IntegerField(null=True, verbose_name='Asistencia'),
        ),
        migrations.AlterField(
            model_name='evalua',
            name='cliente',
            field=models.IntegerField(null=True, verbose_name='Orientaion/Atencion al Cliente'),
        ),
        migrations.AlterField(
            model_name='evalua',
            name='compromiso',
            field=models.IntegerField(null=True, verbose_name='Compromiso'),
        ),
        migrations.AlterField(
            model_name='evalua',
            name='equipo',
            field=models.IntegerField(null=True, verbose_name='Trabajo en Equipo'),
        ),
        migrations.AlterField(
            model_name='evalua',
            name='iniciativa',
            field=models.IntegerField(null=True, verbose_name='Iniciativa'),
        ),
        migrations.AlterField(
            model_name='evalua',
            name='presencia',
            field=models.IntegerField(null=True, verbose_name='Buena Presencia'),
        ),
        migrations.AlterField(
            model_name='evalua',
            name='puntualidad',
            field=models.IntegerField(null=True, verbose_name='Puntualidad'),
        ),
    ]
