# Generated by Django 2.2.1 on 2019-08-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0008_auto_20190719_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='local_id',
        ),
        migrations.AddField(
            model_name='empleado',
            name='local_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sucursal.local'),
            preserve_default=False,
        ),
    ]
