# Generated by Django 2.2.1 on 2019-08-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0009_auto_20190802_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('s_nombre', models.CharField(max_length=100, verbose_name='Segundo Nombre')),
                ('p_apellido', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('s_apellido', models.CharField(max_length=100, verbose_name='Segundo Apellido')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.local')),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
                'ordering': ['p_apellido'],
            },
        ),
    ]
