# Generated by Django 2.2.1 on 2019-09-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0010_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='denominacion',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='s_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='s_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo Nombre'),
        ),
    ]
